1. Memuat Data:
 Import Library Pandas

*   Import Library Pandas
*   Muat dataset 'sales_data.csv' ke dalam DataFrame.

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Semester 6/Data Mining/sales_data.csv')

2. Inpeksi Awal Data:

*   Tampilkan 5 baris pertama dari dataset
*   Gunakan .info() untuk melihat informasi dasar dataset.

In [3]:
df.head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,PRODUCTLINE,PRODUCTCODE,CUSTOMERNAME
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,Motorcycles,S10_1678,Land of Toys Inc.
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,Motorcycles,S10_1678,Reims Collectables
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,Motorcycles,S10_1678,Lyon Souveniers
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,Motorcycles,S10_1678,Toys4GrownUps.com
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,Motorcycles,S10_1678,Corporate Gift Ideas Co.

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ORDERNUMBER      2823 non-null   int64
 1   QUANTITYORDERED  2823 non-null   int64
 2   PRICEEACH        2823 non-null   float64
 3   ORDERLINENUMBER  2823 non-null   int64
 4   SALES            2823 non-null   float64
 5   ORDERDATE        2823 non-null   object
 6   STATUS           2823 non-null   object
 7   PRODUCTLINE      2823 non-null   object
 8   PRODUCTCODE      2823 non-null   object
 9   CUSTOMERNAME     2823 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 220.7+ KB

3. Analisis Deskriptif:
*   Hitung total unit terjual menggunakan .sum() pada kolom Sales
*   Temukan rata-rata unit terjual per transaksi.

In [5]:
df['SALES'].sum()

10032628.85

In [7]:
sales = df['SALES'].mean()
quantity = df['QUANTITYORDERED'].mean()

print(sales)
print(quantity)

3553.889071909316
35.09280906836698