1. Buatlah sebuah fungsi yang menerima list sebagai parameter dan melakukan operasi berikut:
    a. Menambahkan 4 elemen numerik acak.
    b. Menghapus elemen di indeks ganjil.
    c. Membalik urutan elemen dalam list.
    d. Menggandakan elemen pertama dan menambahkannya ke akhir list.
    e. Mencari dan menghapus elemen dengan nilai terkecil dalam list.
    f. Mengurutkan list secara ascending.

In [32]:
import random
import numpy as np
import pandas as pd

In [33]:
my_list = [1, 2, 3, 4, 5]

def manipulasi(list):
  # a. Menambahkan 4 elemen numerik acak.
    for i in range(4):
        list.append(random.randint(1, 20))
    print(f"hasil tambah 4 elemen {list}")
  # b. Menghapus elemen di indeks ganjil
    j = len(list) - 1
    while j >= 0:
        if j % 2 == 1:
            del list[j]
        j -= 1
    print(f"hasil hapus index ganjil {list}")
  # c. Membalik urutan elemen dalam list.
    list.reverse()
    print(f"hasil reverse {list}")
  # d. Menggandakan elemen pertama dan menambahkannya ke akhir list.
    list.append(list[0]*2)
    print(f"hasil kali index pertama{list}")
  # e. Mencari dan menghapus elemen dengan nilai terkecil dalam list.
    min_value = min(list)
    list.remove(min_value)
    print(f"hasil hapus value paling kecil {list}")
  # f. Mengurutkan list secara ascending.
    list.sort()
    print(f"hasil sorting ascending {list}")
    return list

new_list = manipulasi(my_list)

hasil tambah 4 elemen [1, 2, 3, 4, 5, 8, 20, 9, 2]
hasil hapus index ganjil [1, 3, 5, 20, 2]
hasil reverse [2, 20, 5, 3, 1]
hasil kali index pertama[2, 20, 5, 3, 1, 4]
hasil hapus value paling kecil [2, 20, 5, 3, 4]
hasil sorting ascending [2, 3, 4, 5, 20]

2. Buatlah sebuah tuple yang berisi pasangan nilai mata pelajaran dan skor ujian siswa, buatlah  sebuah fungsi yang mampu melakukan hal-hal berikut:
a. Menghapus entri yang tidak lengkap atau memiliki nilai kosong.
b. Menghilangkan entri dengan mata pelajaran yang sama, menyisakan hanya skor
tertinggi.
c. Menghitung jumlah total entri yang tersisa.
d. Mengurutkan entri berdasarkan skor dari yang terendah hingga tertinggi.

In [34]:
scores = [('Matematika', '85'),('Biologi', ''),('Kimia', '90'),('Fisika', '80'), ('Matematika', '88'),('Biologi', '95'),('', '100'), ('Fisika', '82')]

In [35]:
def manipulasi_tuple(scores):
  # a. Menghapus entri yang tidak lengkap atau memiliki nilai kosong
    scores_baru = [(mata_pelajaran, skor) for mata_pelajaran, skor in scores if skor.strip() !='' and mata_pelajaran.strip() !='']
  # b. Menghilangkan entri dengan mata pelajaran yang sama, menyisakan hanya skor tertinggi
    highest = {}
    for matpel, skor in scores_baru:
      if matpel not in highest or int(skor)> int(highest[matpel]):
        highest[matpel] = skor
    filtered = [(mapel,skor) for mapel,skor in scores_baru if skor == highest[mapel]]

  # c. Menghitung jumlah total entri yang tersisa
    sum = len(filtered)

  # d. Mengurutkan entri berdasarkan skor dari yang terendah hingga tertinggi.
    filtered.sort(key= lambda x:x[1])
  # print hasil jumlah entri
    print(filtered)
    print(f"jumlah entri tersisa : {sum}")
    return filtered


hasil = manipulasi_tuple(scores)

[('Fisika', '82'), ('Matematika', '88'), ('Kimia', '90'), ('Biologi', '95')]
jumlah entri tersisa : 4

3. Gunakan NumPy untuk membuat sebuah array dengan elemen numerik acak. Kemudian
lakukan :
a. Normalisasi array tersebut menggunakan Min-Max Scaling.
b. Urutkan array tersebut berdasarkan nilai terbesar ke terkecil

In [36]:
#  Membuat array dengan elemen numerik acak
array = np.random.randint(1, 100, size=(2, 2))

#  Menampilkan array awal
print("Array awal:")
print(array)

# 3. Normalisasi Min-Max Scaling
min_value = np.min(array)
max_value = np.max(array)
normalized_array = (array - min_value) / (max_value - min_value)

# 4. Menampilkan array setelah normalisasi
print("\nArray setelah normalisasi Min-Max Scaling:")
print(normalized_array)

# 5. Mengurutkan array dari terbesar ke terkecil
sorted_array = np.sort(normalized_array, axis=None)[::-1]

# 6. Menampilkan array setelah diurutkan
print("\nArray setelah diurutkan dari terbesar ke terkecil:")
print(sorted_array)

Array awal:
[[37  1]
 [58 86]]

Array setelah normalisasi Min-Max Scaling:
[[0.42352941 0.        ]
 [0.67058824 1.        ]]

Array setelah diurutkan dari terbesar ke terkecil:
[1.         0.67058824 0.42352941 0.        ]

a. Tampilkan ringkasan statistik deskriptif untuk kolom numerik yang mencakup nilai
minimum, maksimum, jumlah, rata-rata, standar deviasi, serta nilai kuartil 1, 2, dan 3.
b. Tentukan Top 3 Kota dengan jumlah mobil terjual terbanyak.
c. Tampilkan mobil yang memiliki harga yang sama.
d. Buatlah sebuah kolom baru yang berisi kategori 'Murah', 'Sedang', atau 'Mahal'
berdasarkan harga. Kategorisasi didasarkan pada aturan: harga di bawah kuartil 1
dikategorikan sebagai 'Murah', harga di atas kuartil 3 dikategorikan sebagai 'Mahal', dan
sisanya dikategorikan sebagai 'Sedang'

In [42]:
# Membuat dictionary dengan data
data = {
    "Merek": ["Toyota", "Honda", "Suzuki", "Hyundai", "Mazda", "Ford","BMW","Mercedes","Mitsubhisi","Nissan"],
    "Kota": ["Jakarta", "Bandung", "Jakarta", "Surabaya", "Bandung", "Jakarta","Surabaya","Jakarta","Bandung","Surabaya"],
    "Harga": [200, 150, 120, 180, 220, 250,500,550,200,170],
    "Tahun": [2015, 2016, 2017, 2018, 2015, 2016, 2017, 2018, 2015, 2016],
    "Status": ["Sold", "Sold", "Available", "Sold", "Available", "Sold", "Sold", "Available","Sold","Available"]
}

# Membuat DataFrame dari dictionary
df = pd.DataFrame(data)

# Menampilkan DataFrame
print(df.to_string())

        Merek      Kota  Harga  Tahun     Status
0      Toyota   Jakarta    200   2015       Sold
1       Honda   Bandung    150   2016       Sold
2      Suzuki   Jakarta    120   2017  Available
3     Hyundai  Surabaya    180   2018       Sold
4       Mazda   Bandung    220   2015  Available
5        Ford   Jakarta    250   2016       Sold
6         BMW  Surabaya    500   2017       Sold
7    Mercedes   Jakarta    550   2018  Available
8  Mitsubhisi   Bandung    200   2015       Sold
9      Nissan  Surabaya    170   2016  Available

In [43]:
# Tampilkan ringkasan statistik deskriptif untuk kolom numerik yang mencakup nilai minimum, maksimum, jumlah, rata-rata, standar deviasi, serta nilai kuartil 1, 2, dan 3.
df.describe()

            Harga        Tahun
count   10.000000    10.000000
mean   254.000000  2016.300000
std    147.738508     1.159502
min    120.000000  2015.000000
25%    172.500000  2015.250000
50%    200.000000  2016.000000
75%    242.500000  2017.000000
max    550.000000  2018.000000

In [39]:
# Tentukan Top 3 Kota dengan jumlah mobil terjual terbanyak.
top_3 = df.groupby("Kota").size().reset_index(name = "Jumlah mobil terjual")

top_3 = top_3.sort_values(by="Jumlah mobil terjual", ascending=False)
top_3

       Kota  Jumlah mobil terjual
1   Jakarta                     4
0   Bandung                     3
2  Surabaya                     3

In [46]:
duplicated = df[df.duplicated(subset="Harga", keep = False)]
duplicated

        Merek     Kota  Harga  Tahun Status Kategori Harga
0      Toyota  Jakarta    200   2015   Sold         Sedang
8  Mitsubhisi  Bandung    200   2015   Sold         Sedang

In [44]:
def kategorisasi_harga(harga):
    kuartil1 = df['Harga'].quantile(0.25)
    kuartil3 = df['Harga'].quantile(0.75)
    if harga < kuartil1:
        return 'Murah'
    elif harga > kuartil3:
        return 'Mahal'
    else:
        return 'Sedang'

# Menambahkan kolom baru 'Kategori Harga' berdasarkan kategorisasi harga
df['Kategori Harga'] = df['Harga'].apply(kategorisasi_harga)

# Menampilkan DataFrame dengan kolom baru
print(df.to_string())

        Merek      Kota  Harga  Tahun     Status Kategori Harga
0      Toyota   Jakarta    200   2015       Sold         Sedang
1       Honda   Bandung    150   2016       Sold          Murah
2      Suzuki   Jakarta    120   2017  Available          Murah
3     Hyundai  Surabaya    180   2018       Sold         Sedang
4       Mazda   Bandung    220   2015  Available         Sedang
5        Ford   Jakarta    250   2016       Sold          Mahal
6         BMW  Surabaya    500   2017       Sold          Mahal
7    Mercedes   Jakarta    550   2018  Available          Mahal
8  Mitsubhisi   Bandung    200   2015       Sold         Sedang
9      Nissan  Surabaya    170   2016  Available          Murah